// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprND5eqUOnVuZsCsnOkmno9DYTjH8DbI',
    appId: '1:64599066981:web:5bc008ed5669180e7bb98c',
    messagingSenderId: '64599066981',
    projectId: 'listesdestaches',
    authDomain: 'listesdestaches.firebaseapp.com',
    storageBucket: 'listesdestaches.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeI0R9H10WIRiNsFIx-wxloEiOSxXbrec',
    appId: '1:64599066981:android:2f6ff32c1b4b24e57bb98c',
    messagingSenderId: '64599066981',
    projectId: 'listesdestaches',
    storageBucket: 'listesdestaches.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyQ_X_qF-rdJKIJT3fhZqE0SmgBCX1-mo',
    appId: '1:64599066981:ios:b15a33ea8b0d453e7bb98c',
    messagingSenderId: '64599066981',
    projectId: 'listesdestaches',
    storageBucket: 'listesdestaches.appspot.com',
    iosBundleId: 'com.example.listeDesTaches',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyQ_X_qF-rdJKIJT3fhZqE0SmgBCX1-mo',
    appId: '1:64599066981:ios:504dee56c39fae357bb98c',
    messagingSenderId: '64599066981',
    projectId: 'listesdestaches',
    storageBucket: 'listesdestaches.appspot.com',
    iosBundleId: 'com.example.listeDesTaches.RunnerTests',
  );
}
